title: Kagi Assistant Prompts
description: A collection of useful prompts for Kagi Assistant and other LLMs
baseurl: ""
url: "https://prompts.thelaboratory.cc"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
author: Stirling Campbell

# URL structure
permalink: /:categories/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Collections for prompts
collections:
  prompts:
    output: true
    permalink: /prompts/:name/

future: true
